## Se modifica la configuracion para que el balanceador use el nombre de dominio privado de Railway en lugar de la IP
## Podemos obtener este valor en la pestaña de despliegue de Railway, Settings -> Networking -> Private Networking
eureka:
  instance:
    preferIpAddress: false
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${server.port}
    secure-port: 443
