## Configuration for Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    hostname: back-end-pizza-orders-production.up.railway.app
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: 80
    secure-port: 443

## Instance port
server:
  port: 8082
spring:
  application:
    name: ms-pizza-orders
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: ${DB_PASSWORD}

  
unir:
  app:
    pizza:
      catalogue:
        url: https://ms-pizza-catalogue/pizzas/%s