## Configuration for Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}

## Instance port
server:
  port: ${PORT:8084}
spring:
  application:
    name: ms-pizza-orders
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: ${DB_PASSWORD}


unir:
  app:
    pizza:
      catalogue:
        url: https://ms-pizza-catalogue/pizzas/%s